name = "EconPDEs"
uuid = "a3315474-fad9-5060-8696-cee5f38a87b7"
version = "0.2.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"

[compat]
julia = "â‰¥ 0.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[targets]
test = ["Test", "Distributions"]
